### ISSUE TITLE
Turn off/on features

### ISSUE THREAD

**Issue by bxpana** [mrjackyliang/discord-stonker-bot#2]
Got the bot up and running. Now I'm having an issue of it sending DMs to everyone about posting affiliate links. Every time I post it gives me the gwei for gas prices and top tickers. I might be missing something in the documentation, but I think it would be helpful if you had an option to turn those features off.

**Comment by mrjackyliang** [comment]
I remember you copied the entire configuration for start. To disable it, simply remove it off of the configuration.

**Comment by bxpana** [comment]
Great point! Did that and all seems to be running smoothly now. Thanks again.

**Comment by mrjackyliang** [comment]
Sure thing! Hope you enjoy the bot!
