### ISSUE TITLE
Sweep for banned avatars after join

### ISSUE THREAD

**Issue by bxpana** [mrjackyliang/discord-stonker-bot#3]
The Anti-raid for avatars works when they have the matching avatar when joining the server, but it does not ban the user if you change the avatar after joining. It would be nice to have a sweep feature that scans for when the restricted avatars are used unless I'm missing something.

**Comment by mrjackyliang** [comment]
There is a command for it. Should be `!fd`, `!duplicates`, or `!fetch-duplicates`. If the command doesn't work, you need to enable it.

**Comment by bxpana** [comment]
Does it ban based on the restricted avatars too or only show the duplicate avatars?

**Comment by mrjackyliang** [comment]
It only shows duplicate avatars. But be careful with banning, some may be legitimate. I've seen a lot of duplicate avatars around that were legitimate members. If you need to ban, you can use the bulk ban command.

**Comment by bxpana** [comment]
I don't want to ban users with duplicate avatars, but ones with specific avatars. For example, there are bots that are pretending to be admins that will copy the admin avatar or server image, and DM users to scam them. Are there any features that can stop users from changing their avatars to the restricted ones by running a command?

**Comment by mrjackyliang** [comment]
The avatar hashes differ, so there's no definite way to check. The avatar ban was created to automatically ban accounts made by bots.

What I've learned from imposters is that they tend to have a color that everyone else has. We would attach a role icon and have a color that looks completely different from what the other users have.

Also, I would set up the snitch notifications, best if it was sent to different threads (and set up the thread bumper as well for those threads). When someone changes their username/nickname, the bot would send a message to that thread.

**Comment by bxpana** [comment]
They tend to use some of the same avatar hashes so it would work if they used the avatar when joining, but they've learned to switch their username and avatar after joining. 

I have a bot that does some sort of snitch notifications, but I'm not always on to monitor. Either way the duplicate avatar function is nice and helps me narrow down who might be scamming next.

**Comment by mrjackyliang** [comment]
What you can try is run a fetch members command when possible: `!fm string [hash]`

It's not automated but definitely helps if it's not a lot of avatar hashes you are checking. Best yet, what you can do is have a python script that controls a secondary device to query those hashes automatically for you.

**Comment by bxpana** [comment]
Cool, great suggestions! Thanks again for your patience, time, and always quick responses.

**Comment by mrjackyliang** [comment]
Sure thing! Glad to help out :)

**Comment by mrjackyliang** [comment]
> They tend to use some of the same avatar hashes so it would work if they used the avatar when joining, but they've learned to switch their username and avatar after joining.
> 
> I have a bot that does some sort of snitch notifications, but I'm not always on to monitor. Either way the duplicate avatar function is nice and helps me narrow down who might be scamming next.

Just letting you know the latest version (`v2.1.1`) includes a feature to ping any member of your choice in a channel if their "keyword" were to be used.

**Comment by bxpana** [comment]
Thanks for the heads up!
